version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: subscription_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  subscription-service:
    build: .
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/subscription_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      CRM_STUB_ENABLED: "true"  # ✅ ВСЕГДА ЗАГЛУШКА В DOCKER
    depends_on:
      - postgres

volumes:
  pgdata: